package panels.search;

import clas.AppData;
import clas.SearchBox;
import clas.db.DatabaseHandler;
import clas.db.SearchHandler;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**
 *
 * @author Lobdown.com
 */
public class SearchDate extends javax.swing.JPanel {

    SearchHandler search = new SearchHandler();
    SearchBox box;
    DatabaseHandler db;
    Image img;

    /**
     * Creates new form SearchDate
     */
    public SearchDate() {
        initComponents();
        this.img = new ImageIcon(AppData.class.getResource("/images/background_search.jpg")).getImage();
        setName("جستجو بر اساس تاریخ");
        startYear.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        endYear.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        startYear.setEditor(new JSpinner.NumberEditor(startYear, "#"));
        endYear.setEditor(new JSpinner.NumberEditor(endYear, "#"));
        datePanel.setOpaque(true);
        datePanel.setBackground(new Color(0, 0, 0, 0.3f));
        
        db = new DatabaseHandler();
        box = new SearchBox(userId, searchBox, db);

        userId.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                if (userId.getText().length() > 0) {
                    box.search(userId.getText());
                }
            }
        });
        
        
    }

    @Override
    public void paintComponent(Graphics g) {
        g.drawImage(img, 0, 0, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        startYear = new javax.swing.JSpinner();
        endYear = new javax.swing.JSpinner();
        searchButton = new javax.swing.JButton();
        startMonth = new javax.swing.JComboBox();
        endMonth = new javax.swing.JComboBox();
        startDay = new javax.swing.JComboBox();
        endDay = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        oneDaySearch = new javax.swing.JCheckBox();
        userId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        searchBox = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        datePanel.setPreferredSize(new java.awt.Dimension(550, 250));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("از تاریخ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("تا تاریخ");

        startYear.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1397), Integer.valueOf(1300), null, Integer.valueOf(1)));

        endYear.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1397), Integer.valueOf(1300), null, Integer.valueOf(1)));

        searchButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchButton.setText("جستجو");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        startMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "فروردین", "اردیبهشت", "خرداد", "تیر", "مرداد", "شهریور", "مهر", "آبان", "آذر", "دی", "بهمن", "اسفند" }));

        endMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "فروردین", "اردیبهشت", "خرداد", "تیر", "مرداد", "شهریور", "مهر", "آبان", "آذر", "دی", "بهمن", "اسفند" }));

        startDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        endDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("جستجو در یک روز باشد");

        oneDaySearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oneDaySearch.setOpaque(false);
        oneDaySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneDaySearchActionPerformed(evt);
            }
        });

        userId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("شماره پرونده (اختیاری):");

        searchBox.setOpaque(false);
        searchBox.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout datePanelLayout = new javax.swing.GroupLayout(datePanel);
        datePanel.setLayout(datePanelLayout);
        datePanelLayout.setHorizontalGroup(
            datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datePanelLayout.createSequentialGroup()
                        .addComponent(searchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                        .addComponent(oneDaySearch)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3))
                    .addGroup(datePanelLayout.createSequentialGroup()
                        .addGroup(datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(endYear, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(startYear))
                        .addGap(18, 18, 18)
                        .addGroup(datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endMonth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datePanelLayout.createSequentialGroup()
                        .addGroup(datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(datePanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(endDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(startDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );
        datePanelLayout.setVerticalGroup(
            datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBox, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(startYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(endYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButton)
                    .addComponent(jLabel3)
                    .addComponent(oneDaySearch))
                .addContainerGap())
        );

        add(datePanel, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void oneDaySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneDaySearchActionPerformed
        if (oneDaySearch.isSelected()) {
            endYear.setEnabled(false);
            endMonth.setEnabled(false);
            endDay.setEnabled(false);
        } else {
            endYear.setEnabled(true);
            endMonth.setEnabled(true);
            endDay.setEnabled(true);
        }
    }//GEN-LAST:event_oneDaySearchActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String start = startYear.getValue() + "-" + (startMonth.getSelectedIndex() + 1) + "-" + (startDay.getSelectedIndex() + 1);
        String end = endYear.getValue() + "-" + (endMonth.getSelectedIndex() + 1) + "-" + (endDay.getSelectedIndex() + 1);
        if (oneDaySearch.isSelected()) {
            if (userId.getText().length() > 0) {
                ResultSet r = search.searchOneDayUser(userId.getText(), start);
                if (r != null) {
                    try {
                        AppData.changeSearchFrame(new SearchResult(r));
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "نتایجی برای این تاریخ وجود ندارد");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "نتایجی برای این تاریخ وجود ندارد");
                }
            } else {
                ResultSet r = search.searchOneDay(start);
                if (r != null) {
                    try {
                        AppData.changeSearchFrame(new SearchResult(r));
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "نتایجی برای این تاریخ وجود ندارد");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "نتایجی برای این تاریخ وجود ندارد");
                }
            }
        } else {
            if (userId.getText().length() > 0) {
                ResultSet r = search.searchBetween(userId.getText(), start, end);
                if (r != null) {
                    try {
                        AppData.changeSearchFrame(new SearchResult(r));
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "نتایجی برای این تاریخ وجود ندارد");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "نتایجی برای این تاریخ وجود ندارد");
                }
            } else {
                ResultSet r = search.searchBetween(start, end);
                if (r != null) {
                    try {
                        AppData.changeSearchFrame(new SearchResult(r));
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "نتایجی برای این تاریخ وجود ندارد");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "نتایجی برای این تاریخ وجود ندارد");
                }
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel datePanel;
    private javax.swing.JComboBox endDay;
    private javax.swing.JComboBox endMonth;
    private javax.swing.JSpinner endYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JCheckBox oneDaySearch;
    private javax.swing.JPanel searchBox;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox startDay;
    private javax.swing.JComboBox startMonth;
    private javax.swing.JSpinner startYear;
    private javax.swing.JTextField userId;
    // End of variables declaration//GEN-END:variables
}
