package panels.search;

import panels.details.Details;
import clas.AppData;
import clas.SearchBox;
import clas.db.DatabaseHandler;
import clas.db.SearchHandler;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 * CLASS ID = 2000-1
 *
 * @author Lobdown.com
 */
public class SearchDefault extends javax.swing.JPanel implements KeyListener, FocusListener {

    private Image img;
    SearchHandler search = new SearchHandler();

    SearchBox box;
    DatabaseHandler db;

    /**
     * Creates new form SearchDefault
     */
    public SearchDefault() {
        initComponents();
        this.img = new ImageIcon(AppData.class.getResource("/images/background_search.jpg")).getImage();
        setName("جستجو");
        defaultPanel.setOpaque(true);
        defaultPanel.setBackground(new Color(0, 0, 0, 0.3f));

        query.addFocusListener(this);

        db = new DatabaseHandler();
        box = new SearchBox(query, searchBox, db);

        query.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                if (query.getText().length() > 0) {
                    box.search(query.getText());
                }
            }
        });

    }

    @Override
    public void paintComponent(Graphics g) {
        g.drawImage(img, 0, 0, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        defaultPanel = new javax.swing.JPanel();
        query = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        searchBox = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userEdit = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(663, 500));
        setLayout(new java.awt.GridBagLayout());

        defaultPanel.setPreferredSize(new java.awt.Dimension(400, 200));

        query.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        query.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                queryKeyTyped(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchButton.setText("جستجو");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchBox.setOpaque(false);
        searchBox.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("شماره پرونده");

        userEdit.setText("ویرایش");
        userEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout defaultPanelLayout = new javax.swing.GroupLayout(defaultPanel);
        defaultPanel.setLayout(defaultPanelLayout);
        defaultPanelLayout.setHorizontalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(defaultPanelLayout.createSequentialGroup()
                        .addComponent(searchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userEdit)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, defaultPanelLayout.createSequentialGroup()
                        .addGroup(defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(defaultPanelLayout.createSequentialGroup()
                                .addComponent(query, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addComponent(searchBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))))
        );
        defaultPanelLayout.setVerticalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(query, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(userEdit))
                .addContainerGap())
        );

        add(defaultPanel, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        searchPlease();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void queryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_queryKeyTyped
    }//GEN-LAST:event_queryKeyTyped

    private void userEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userEditActionPerformed

    public void searchPlease() {
        if (query.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "فیلد مربوطه را پر کنید", "خطا در پردازش", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            int id = Integer.parseInt(query.getText());
            ResultSet r = search.getUsers(id);
            if (r != null) {
                r.next();
                AppData.changeSingleSearchFrame(new Details(r));
            } else {
                JOptionPane.showMessageDialog(null, "بیماری با این شماره پرونده وجود ندارد", "خطا در پردازش", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "شماره پرونده باید به صورت عدد وارد شود", "خطا در پردازش", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel defaultPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField query;
    private javax.swing.JPanel searchBox;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton userEdit;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {

    }

    @Override
    public void keyPressed(KeyEvent e) {

    }

    @Override
    public void keyReleased(KeyEvent e) {
        if (e.getKeyCode() == KeyEvent.VK_ENTER) {
            searchPlease();
        }
    }

    @Override
    public void focusGained(FocusEvent e) {
        JTextField f;
        f = (JTextField) e.getComponent();
        f.selectAll();
    }

    @Override
    public void focusLost(FocusEvent e) {

    }
}
