package panels.details;

import clas.db.UserModel;
import javax.swing.JOptionPane;


/**
 *
 * @author Lobdown.com
 */
public class DetailsLastVisit extends javax.swing.JPanel {

    UserModel user;
    
    /**
     * Creates new form Details
     * @param user
     */
    public DetailsLastVisit(UserModel user) {
        initComponents();
        setName("جزئیات آخرین ویزیت");
        this.user = user;
        initUserInfo();
        dozPanel.add(new DozPanel(user));
        if(!user.hasVisitData) {
            JOptionPane.showMessageDialog(null, "هیچ ویزیتی برای این بیمار وجود ندارد");
        }
    }
    
    private void initUserInfo() {
        this.userName.setText(user.firstName + " " + user.lastName);
        this.userId.setText(user.id);
        this.userLastVisit.setText(user.visit_date);
        this.drugPeriod.setText(user.day);
        this.nextVisit.setText(user.next_visit);
        this.visitId.setText(user.visit_id);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userLastVisit = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        drugPeriod = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nextVisit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        visitId = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        visitDay = new javax.swing.JLabel();
        dozPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(400, 150));
        setLayout(new java.awt.BorderLayout());

        northPanel.setPreferredSize(new java.awt.Dimension(400, 200));
        northPanel.setLayout(new java.awt.GridBagLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(450, 150));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("شماره پرونده: ");

        userId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userId.setText("0000000");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("نام بیمار:");

        userName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userName.setText("نام و نام خانوادگی");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("آخرین مراجعه:");

        userLastVisit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userLastVisit.setText("0000-00-00");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("تعداد روز دارو:");

        drugPeriod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        drugPeriod.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("تاریخ مراجعه بعدی:");

        nextVisit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nextVisit.setForeground(new java.awt.Color(0, 204, 0));
        nextVisit.setText("0000-00-00");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("شناسه ویزیت:");

        visitId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        visitId.setText("0000000");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("روز مراجعه");

        visitDay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        visitDay.setForeground(new java.awt.Color(255, 51, 51));
        visitDay.setText("آزاد");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(userName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(drugPeriod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(visitId)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(userId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(userLastVisit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(visitDay)
                            .addComponent(nextVisit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userId)
                    .addComponent(jLabel2)
                    .addComponent(userName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(userLastVisit)
                    .addComponent(jLabel6)
                    .addComponent(drugPeriod))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nextVisit)
                    .addComponent(jLabel3)
                    .addComponent(visitId))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(visitDay))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        northPanel.add(jPanel1, new java.awt.GridBagConstraints());

        add(northPanel, java.awt.BorderLayout.PAGE_START);

        dozPanel.setLayout(new java.awt.BorderLayout());
        add(dozPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dozPanel;
    private javax.swing.JLabel drugPeriod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nextVisit;
    private javax.swing.JPanel northPanel;
    private javax.swing.JLabel userId;
    private javax.swing.JLabel userLastVisit;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel visitDay;
    private javax.swing.JLabel visitId;
    // End of variables declaration//GEN-END:variables
}
