package panels.details;

import clas.AppData;
import clas.db.UserModel;
import java.awt.ComponentOrientation;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JTabbedPane;

/**
 *
 * @author Lobdown.com
 */
public class Details extends javax.swing.JPanel {

    /**
     * Creates new form Details
     * @param resultSet an user info
     */
    public Details(ResultSet resultSet) {
        initComponents();
        backButton.setIcon(new ImageIcon(getClass().getResource("/images/icon_back.png")));
        JTabbedPane tabs = new JTabbedPane();
        tabs.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        
        UserModel user = new UserModel(resultSet);
        
        tabs.add(new DetailsLastVisit(user));
        tabs.add(new DetailsHistory(user));
        //tabs.add(new DetailsVisit(user));
        
        add(tabs);
        validate();
        repaint();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 55));

        backButton.setFocusable(false);
        backButton.setMaximumSize(new java.awt.Dimension(33, 33));
        backButton.setMinimumSize(new java.awt.Dimension(33, 33));
        backButton.setPreferredSize(new java.awt.Dimension(33, 32));
        backButton.setRequestFocusEnabled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(357, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        AppData.singleSearchFrame.dispose();
        validate();
        repaint();
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
