package panels.details;

import clas.AppData;
import clas.HistoryTable;
import clas.db.DatabaseHandler;
import clas.db.UserModel;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lobdown.com
 */
public class DetailsHistory extends javax.swing.JPanel {

    JTable table = new JTable();
    UserModel user;
    DatabaseHandler handler;

    /**
     * Creates new form WelcomeDetails
     *
     * @param user
     */
    public DetailsHistory(UserModel user) {
        initComponents();
        setName("سوابق مراجعه");
        this.user = user;
        ResultSet r = user.getHistory();
        if (r != null) {
            table = new HistoryTable();
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            try {
                while (r.next()) {
                    Object[] row = new Object[2];
                    row[0] = r.getObject(1);
                    row[1] = r.getObject(3);
                    model.addRow(row);
                }
            } catch (Exception e) {
            }
        } else {
            table = new JTable();
        }

        table.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {

                if (evt.getClickCount() == 2) {
                    showVisitDetails();
                }

            }
        });

        JScrollPane js = new JScrollPane(table);
        jPanel2.add(js);

    }

    private void showVisitDetails() {
        if (table.getSelectedRow() != -1) {
            handler = new DatabaseHandler();
            ResultSet r = handler.getVisit(table.getValueAt(table.getSelectedRow(), 0).toString());
            ShowVisitDetails visit = new ShowVisitDetails(new UserModel(r, true));
            AppData.changeVisitFrame(visit);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jButton1.setText("جزئیات");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, java.awt.BorderLayout.PAGE_END);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        showVisitDetails();

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
