package panels.other;

import clas.AppData;
import clas.TodayUserTable;
import java.awt.BorderLayout;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Lobdown.com
 */
public class Welcome extends javax.swing.JPanel {

    JTable table;
    public static JPanel p;

    /**
     * Creates new form MainPanel
     */
    public Welcome() {
        initComponents();
        String data[][] = {
            {"7794561", "احمد مشیری", "1397-12-1"},
            {"7894213", "احمد مشیری", "1397-12-1"},
            {"6629354", "احمد مشیری", "1397-12-1"},
            {"1937545", "احمد مشیری", "1397-12-1"},
            {"2854693", "احمد مشیری", "1397-12-1"},
            {"6452896", "رضا صابری", "1397-11-29"},
            {"3211987", "نوید رضایی", "1937-12-15"},
            {"7894213", "نوید رضایی", "1937-12-15"},
            {"4399685", "نوید رضایی", "1937-12-15"},
            {"5565845", "نوید رضایی", "1937-12-15"},
            {"1123544", "نوید رضایی", "1937-12-15"},
            {"9878544", "نوید رضایی", "1937-12-15"},
            {"9744325", "نوید رضایی", "1937-12-15"},
            {"1123658", "نوید رضایی", "1937-12-15"},
            {"8898541", "نوید رضایی", "1937-12-15"},
            {"3365214", "نوید رضایی", "1937-12-15"},
            {"7452195", "نوید رضایی", "1937-12-15"},
            {"3365423", "نوید رضایی", "1937-12-15"},
            {"3963666", "نوید رضایی", "1937-12-15"}
        };

        String column[] = {"شماره پرونده", "نام", "آخرین مراجعه"};

        table = new TodayUserTable(data, column);

        JScrollPane sp = new JScrollPane(table);

        listPanel.add(sp, BorderLayout.CENTER);

        table.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    detailsAction();
                }
            }
        });

        table.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_SPACE) {
                    detailsAction();
                }
            }

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listPanel = new javax.swing.JPanel();
        toolsPanel = new javax.swing.JPanel();
        detail = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        listPanel.setOpaque(false);
        listPanel.setLayout(new java.awt.BorderLayout());
        add(listPanel, java.awt.BorderLayout.CENTER);

        toolsPanel.setLayout(new java.awt.GridLayout(1, 5));

        detail.setText("جزئیات");
        detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailActionPerformed(evt);
            }
        });
        toolsPanel.add(detail);

        add(toolsPanel, java.awt.BorderLayout.PAGE_END);

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 36));

        jLabel1.setText("لیست مراجعه کنندگان امروز");

        jLabel2.setText("1397-05-09");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailActionPerformed
        detailsAction();
    }//GEN-LAST:event_detailActionPerformed

    private void detailsAction() {
        if (table.getSelectedRow() != -1) {
            AppData.USER = (String) table.getValueAt(table.getSelectedRow(), 0);
           // AppData.changeDetailsFrame(new Details(null));
            setVisible(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton detail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel listPanel;
    private javax.swing.JPanel toolsPanel;
    // End of variables declaration//GEN-END:variables
}
