package panels.user;

import clas.db.UserHandler;
import java.awt.ComponentOrientation;
import javax.swing.JOptionPane;

/**
 *
 * @author Lobdown..com
 */
public class UserEdit extends javax.swing.JPanel {

    String data[];
    
    
    /**
     * Creates new form UserEdit
     * @param data
     */
    public UserEdit(String[] data) {
        initComponents();
        this.data = data;
        jTextField2.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jTextField3.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jTextField1.setText(data[0]);
        jTextField2.setText(data[1]);
        jTextField3.setText(data[2]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ویرایش مشخصات بیمار");

        jLabel2.setText("شماره پرونده");

        jLabel3.setText("نام");

        jLabel4.setText("نام خانوادگی");

        jButton1.setText("به روزرسانی");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("توجه: با تغییر شماره پرونده به دلیل به روز رسانی شماره پرونده در جدول مراجعه کنندگان");

        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("به روز رسانی ممکن است مقداری طول بکشد. لطفا صبور باشید");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                .addComponent(jTextField1)
                                .addComponent(jTextField3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        add(jPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (checkForm()) {
            UserHandler handler = new UserHandler();
            if (id_changed()) {
                // check user_id is not exist
                if (handler.userExists(jTextField1.getText())) {
                    JOptionPane.showMessageDialog(this, "این شماره پرونده قبلا ثبت شده است", "مشکل در ورود اطلاعات", JOptionPane.ERROR_MESSAGE);
                } else {
                    // update user_fname user_lname user_id WHERE user_id = user_id
                    handler.updateUserId(data[0], jTextField1.getText(), jTextField2.getText(), jTextField3.getText());
                    JOptionPane.showMessageDialog(this, "به روز رسانی اطلاعات با موفقیت انجام شد", "انجام عملیات", JOptionPane.INFORMATION_MESSAGE);
                    // Update User List table
                }
            } else {
                handler.updateUser(Integer.parseInt(jTextField1.getText()), jTextField2.getText(), jTextField3.getText());
                JOptionPane.showMessageDialog(this, "به روز رسانی اطلاعات با موفقیت انجام شد", "انجام عملیات", JOptionPane.INFORMATION_MESSAGE);
                // update user_name and user_afmily where user_id = userId
            }
        } else {
            JOptionPane.showMessageDialog(this, "تمامی فیلد ها باید پر شود و یا اطلاعات وارد شده مجاز نمی باشد، در صورت عدم تغییر اطلاعات. به روز رسانی صورت نخواهئ گرفت.", "اخطار در ورود اطلاعات", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean checkForm() {
        if (jTextField1.getText().length() > 0 && jTextField2.getText().length() > 0 && jTextField3.getText().length() > 0) {
             if (jTextField1.getText().equalsIgnoreCase(data[0]) && jTextField2.getText().equalsIgnoreCase(data[1]) && jTextField3.getText().equalsIgnoreCase(data[2])) {
                 return false;
             }
            try {
                Integer.parseInt(jTextField1.getText());
                return true;
            } catch (Exception e) {
                return false;
            }
        }
        return false;
    }
    
    public boolean id_changed() {
        if (jTextField1.getText().equalsIgnoreCase(data[0])) {
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
