package panels.user;

import clas.AppData;
import clas.db.UserHandler;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Lobdown.com
 */
public class UserAdd extends javax.swing.JPanel {

    User user;
    Image img;

    /**
     * Creates new form UserAdd
     *
     * @param user
     */
    public UserAdd(User user) {
        initComponents();
        this.img = new ImageIcon(AppData.class.getResource("/images/background_add_user.jpg")).getImage();
        this.user = user;
        setName("افزودن بیمار");
        jPanel1.setOpaque(true);
        jPanel1.setBackground(new Color(0, 0, 0, 0.3f));
        shanbe.setOpaque(false);
        yekShanbe.setOpaque(false);
        doShanbe.setOpaque(false);
        seShanbe.setOpaque(false);
        chaharShanbe.setOpaque(false);
        panjShanbe.setOpaque(false);
        nadarad.setOpaque(false);
        azad.setOpaque(false);        
        firstName.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        lastName.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        firstName.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    addUser();
                }
            }

        }
        );
        lastName.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    addUser();
                }
            }

        }
        );
        userId.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    addUser();
                }
            }

        });
//        userDay.addKeyListener(new KeyAdapter() {
//            @Override
//            public void keyPressed(KeyEvent e) {
//                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
//                    addUser();
//                }
//            }
//
//        }
//        );
        userTell.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    addUser();
                }
            }

        }
        );
    }

    @Override
    public void paintComponent(Graphics g) {
        g.drawImage(img, 0, 0, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        userId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        userTell = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        shanbe = new javax.swing.JCheckBox();
        yekShanbe = new javax.swing.JCheckBox();
        doShanbe = new javax.swing.JCheckBox();
        seShanbe = new javax.swing.JCheckBox();
        chaharShanbe = new javax.swing.JCheckBox();
        panjShanbe = new javax.swing.JCheckBox();
        nadarad = new javax.swing.JCheckBox();
        azad = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(600, 400));
        setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("نام");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("نام خانوادگی");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("شماره پرونده");

        firstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        firstName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lastName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        userId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("روز مراجعه");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("شماره همراه");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("افزودن");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        shanbe.setForeground(new java.awt.Color(255, 255, 255));
        shanbe.setText("شنبه");

        yekShanbe.setForeground(new java.awt.Color(255, 255, 255));
        yekShanbe.setText("یکشنبه");

        doShanbe.setForeground(new java.awt.Color(255, 255, 255));
        doShanbe.setText("دوشنبه");

        seShanbe.setForeground(new java.awt.Color(255, 255, 255));
        seShanbe.setText("سه شنبه");

        chaharShanbe.setForeground(new java.awt.Color(255, 255, 255));
        chaharShanbe.setText("چهارشنبه");

        panjShanbe.setForeground(new java.awt.Color(255, 255, 255));
        panjShanbe.setText("پنج شنبه");

        nadarad.setForeground(new java.awt.Color(255, 255, 255));
        nadarad.setText("ندارد");

        azad.setForeground(new java.awt.Color(255, 255, 255));
        azad.setText("آزاد");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(firstName)
                                    .addComponent(lastName)
                                    .addComponent(userId, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                    .addComponent(userTell)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(doShanbe)
                                    .addComponent(panjShanbe))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yekShanbe)
                                    .addComponent(jLabel1)
                                    .addComponent(chaharShanbe)
                                    .addComponent(nadarad))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(shanbe)
                                    .addComponent(seShanbe)
                                    .addComponent(azad)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(userId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(userTell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yekShanbe)
                    .addComponent(doShanbe)
                    .addComponent(shanbe))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chaharShanbe)
                    .addComponent(panjShanbe)
                    .addComponent(seShanbe))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nadarad)
                    .addComponent(azad))
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        add(jPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addUser();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addUser() {
        String name, family, code, tell, day;
        name = firstName.getText();
        family = lastName.getText();
        code = userId.getText();
        day = getDays();
        tell = userTell.getText();
        if (name.length() > 0 && family.length() > 0 && code.length() > 0) {
            try {
                int id = Integer.parseInt(code);
                UserHandler user = new UserHandler();
                int result = user.addUser(id, name, family, day, tell);
                if (result == 1) {
                    // JOptionPane.showMessageDialog(null, "اطلاعات با موفقیت ثبت شد", "", JOptionPane.INFORMATION_MESSAGE);
                    firstName.setText("");
                    lastName.setText("");
                    userId.setText("");
                    userTell.setText("");
                    cleanDays();
                    firstName.requestFocus();
                    this.user.updatePanel();
                    user.closeConnection();
                } else {
                    userId.requestFocus();
                    userId.selectAll();
                    JOptionPane.showMessageDialog(null, "شماره پرونده تکراری می باشد", "اخطار", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "شماره پرونده باید عدد باشد", "اخطار", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "تمامی فیلد ها پر شود", "اخطار", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private String getDays() {
        String days = "";
        JCheckBox[] box = {shanbe, yekShanbe, doShanbe, seShanbe, chaharShanbe, panjShanbe, azad, nadarad};
    
        for (JCheckBox checkbox: box) {
            if (checkbox.isSelected()) {
                String value = "";
                switch (checkbox.getText()) {
                    case "شنبه":
                        value = "1";
                        break;
                    case "یکشنبه":
                        value = "2";
                        break;
                    case "دوشنبه":
                        value = "3";
                        break;
                    case "سه شنبه":
                        value = "4";
                        break;
                    case "چهارشنبه":
                        value = "5";
                        break;
                    case "پنج شنبه":
                        value = "6";
                        break;
                    case "آزاد":
                        value = "7";
                        break;
                    case "ندارد":
                        value = "8";
                        break;
                    default:
                        value = "8";
                }
                if (days.length() == 0) {
                    days = value;
                } else {
                    days += "," + value;
                }
            }
        }
        // default is ندارد
        return days.length() > 0 ? days : "8";
    }
    
    private void cleanDays() {
        JCheckBox[] box = {shanbe, yekShanbe, doShanbe, seShanbe, chaharShanbe, panjShanbe, azad, nadarad};
        for (JCheckBox checkbox : box) {
            checkbox.setSelected(false);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox azad;
    private javax.swing.JCheckBox chaharShanbe;
    private javax.swing.JCheckBox doShanbe;
    private javax.swing.JTextField firstName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastName;
    private javax.swing.JCheckBox nadarad;
    private javax.swing.JCheckBox panjShanbe;
    private javax.swing.JCheckBox seShanbe;
    private javax.swing.JCheckBox shanbe;
    private javax.swing.JTextField userId;
    private javax.swing.JTextField userTell;
    private javax.swing.JCheckBox yekShanbe;
    // End of variables declaration//GEN-END:variables
}
